apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-200208-qld2-service
spec:
  selector:
    app: enterprise-system-200208-qld2
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
